name: Build Release
on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup proper PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Zip the plugin
      run: zip -r tumblr-theme-garden.zip . -x ".*" -x "bin/*" -x "**/tests/*" -x "**/run-tests.sh" -x "*.dist"

    - name: Upload plugin zip as release asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} tumblr-theme-garden.zip
